server:
  port: 8800

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: cll123456
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC
      minimum-idle: 2
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-test-query: SELECT 1
      connection-timeout: 30000


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cll.demo.example.entity
  type-enums-package: com.cll.demo.example.enums
  global-config:
    sql-parser-cache: true
    db-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_null
      db-type: mysql
      table-prefix: t_

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #call-setters-on-nulls: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    default-executor-type: reuse
    #return-instance-for-empty-row: true

